name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish Gabay to PyPI
    runs-on: ubuntu-latest
    permissions:
      # This permission is required for Trusted Publishing (OIDC)
      id-token: write
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/p/gabay

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install build dependencies
      run: python -m pip install --upgrade pip build

    - name: Build binary wheel and source tarball
      run: python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No need for API tokens with OIDC!
